# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marek Marusic
username: Marek Marusic
email: marek.marusic@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Marek Marusic - Software Engineer passionate about technology, who is always looking forward to improve himself and learn something new.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mmarusic.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mmarus
linkedin_username: marekmarusic
userPhoto: /assets/img/user.jpg
aboutMe: "
  passionate about technology, who is always looking forward to improve himself and learn something new.

I am trying to stay at the bleeding edge of tech industry so that I can find and invest time in really world shaping technologies and maybe create some. 

I love learning, building and passing on the knowledge so that others can go through the same realization but shorten the time for them.

I always try to be approachable, kind and helpful to other team members and I am always open to new ideas and suggestions."


user_description: passionate about technology, who is always looking forward to improve himself and learn something new.
profession: Software Engineer

disqus_username: mmarusic

# Build settings
markdown: kramdown
theme: materialize-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
