# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marek Marusic
username: Marek Marusic
email: marek.marusic@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mmarusic.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mmarus
fb_username: marek.marusic
twitter_username: Maaaareeeek
instagram_username: maareekm
linkedin_username: marekmarusic
userPhoto: /assets/img/user.jpg
aboutMe: "My first contact with development was during my elementary school when I was trying out some HTML and CSS.
Then during my high school I started to learn PHP, MySQL and C from books my father bought me and the education of my self and the software development became my passion."

#As a self-motivated and responsible person I love solving problems.
#At the same time, I am looking forward to challenging and growth oriented tasks that help to prove the best of my ability in achieving the objective of the job.
user_description: Software Engineer passionate about technology, who is always looking forward to improve himself and learn something new.
profession: Software Developer

disqus_username: mmarusic

# Build settings
markdown: kramdown
theme: materialize-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
